// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {BrainfuckVM} from "../src/BrainfuckVM.sol";
import {CartridgeRegistry} from "../src/CartridgeRegistry.sol";

/// @title TamagotchiTest
/// @notice Tests the Tamagotchi BF cartridge running on-chain.
contract TamagotchiTest is Test {
    BrainfuckVM public bfVM;
    CartridgeRegistry public registry;

    uint256 public tamagotchiId;
    uint256 public constant MAX_STEPS = 50_000;

    bytes public tamagotchiProgram;

    function setUp() public {
        bfVM = new BrainfuckVM(30_000);
        registry = new CartridgeRegistry(address(bfVM));

        // Load the BF program from the generated hex (v2 - pointer-safe)
        // Generated by: python3 scripts/generate_tamagotchi.py
        tamagotchiProgram = hex"2c3e2c3e2c3e2c3e2c3e2b3c3c3c3c3c2d5b2d3e3e3e3e3e3e3e2b3e2b3c3c3c3c3c3c3c3c5d3e3e3e3e3e3e3e3e5b2d3c3c3c3c3c3c3c3c2b3e3e3e3e3e3e3e3e5d3c3c2b3e5b3c2d3e5b2d5d5d3c5b3c3c3c3c3c2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d3e2b2b2b2b2b3e3e2b3e3e2d5d5b2d5d3e5b2d5d3e5b2d5d3c3c3c3c3c3c3c3c2d5b2d3e3e3e3e3e3e3e2b3e2b3c3c3c3c3c3c3c3c5d3e3e3e3e3e3e3e3e5b2d3c3c3c3c3c3c3c3c2b3e3e3e3e3e3e3e3e5d3c3c2b3e5b3c2d3e5b2d5d5d3c5b3c3c3c3c2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b3e2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d3c3c2b2b2b2b2b2b2b2b2b2b3e3e3e2b3e3e2d5d5b2d5d3e5b2d5d3e5b2d5d3c3c3c3c3c3c3c3c2d5b2d3e3e3e3e3e3e3e2b3e2b3c3c3c3c3c3c3c3c5d3e3e3e3e3e3e3e3e5b2d3c3c3c3c3c3c3c3c2b3e3e3e3e3e3e3e3e5d3c3c2b3e5b3c2d3e5b2d5d5d3c5b3c3c3c2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b2b3c2d2d2d2d2d3e3e2b3e3e2d5d5b2d5d3e5b2d5d3e5b2d5d3c3c3c3c3c3c5b2d3e3e3e3e3e2b3e2b3c3c3c3c3c3c5d3e3e3e3e3e3e5b2d3c3c3c3c3c3c2b3e3e3e3e3e3e5d3c3c2b3e5b3c2d3e5b2d5d5d3c5b3c2d3e2d5d5b2d5d3e5b2d5d3e5b2d5d3c3c3c3c3c5b2d3e3e3e3e2b3e2b3c3c3c3c3c5d3e3e3e3e3e5b2d3c3c3c3c3c2b3e3e3e3e3e5d3c3c2b3e5b3c2d3e5b2d5d5d3c5b3c2d3e2d5d5b2d5d3e5b2d5d3e5b2d5d3c3c3c3c3c3c3c2e3e2e3e2e3e2e3e2e";

        tamagotchiId = registry.loadCartridge(tamagotchiProgram, "Tamagotchi");
    }

    // ─── Helper ──────────────────────────────────

    function _play(
        uint8 action,
        uint8 hunger,
        uint8 happiness,
        uint8 energy,
        uint8 age
    ) internal returns (bytes memory output) {
        bytes memory input = new bytes(5);
        input[0] = bytes1(action);
        input[1] = bytes1(hunger);
        input[2] = bytes1(happiness);
        input[3] = bytes1(energy);
        input[4] = bytes1(age);

        output = registry.play(tamagotchiId, input, MAX_STEPS);
    }

    function _assertState(
        bytes memory output,
        uint8 expectedHunger,
        uint8 expectedHappiness,
        uint8 expectedEnergy,
        uint8 expectedAge,
        uint8 expectedAlive
    ) internal pure {
        assertEq(output.length, 5, "Output should be 5 bytes");
        assertEq(uint8(output[0]), expectedHunger, "Hunger mismatch");
        assertEq(uint8(output[1]), expectedHappiness, "Happiness mismatch");
        assertEq(uint8(output[2]), expectedEnergy, "Energy mismatch");
        assertEq(uint8(output[3]), expectedAge, "Age mismatch");
        assertEq(uint8(output[4]), expectedAlive, "Alive mismatch");
    }

    // ─── Feed Action ─────────────────────────────

    function test_Feed() public {
        bytes memory output = _play(1, 100, 50, 80, 10);
        _assertState(output, 70, 55, 80, 11, 1);
    }

    function test_FeedLowHunger() public {
        bytes memory output = _play(1, 20, 50, 80, 10);
        _assertState(output, 246, 55, 80, 11, 1);
    }

    // ─── Play Action ─────────────────────────────

    function test_Play_() public {
        bytes memory output = _play(2, 50, 30, 100, 10);
        _assertState(output, 60, 50, 85, 11, 1);
    }

    function test_PlayLowEnergy() public {
        bytes memory output = _play(2, 50, 30, 10, 10);
        _assertState(output, 60, 50, 251, 11, 1);
    }

    // ─── Sleep Action ────────────────────────────

    function test_Sleep() public {
        bytes memory output = _play(3, 50, 80, 30, 10);
        _assertState(output, 50, 75, 60, 11, 1);
    }

    function test_SleepLowHappiness() public {
        bytes memory output = _play(3, 50, 5, 30, 10);
        _assertState(output, 50, 0, 60, 11, 0);
    }

    // ─── Status Action ───────────────────────────

    function test_Status() public {
        bytes memory output = _play(4, 50, 80, 60, 10);
        _assertState(output, 50, 80, 60, 10, 1);
    }

    function test_StatusDeadPet() public {
        bytes memory output = _play(4, 50, 0, 60, 10);
        _assertState(output, 50, 0, 60, 10, 0);
    }

    // ─── Death Conditions ────────────────────────

    function test_DeathByZeroHappiness() public {
        bytes memory output = _play(4, 50, 0, 60, 10);
        assertEq(uint8(output[4]), 0, "Should be dead");
    }

    function test_DeathByZeroEnergy() public {
        bytes memory output = _play(4, 50, 80, 0, 10);
        assertEq(uint8(output[4]), 0, "Should be dead");
    }

    function test_AliveWithGoodStats() public {
        bytes memory output = _play(4, 50, 100, 100, 10);
        assertEq(uint8(output[4]), 1, "Should be alive");
    }

    // ─── Full Lifecycle ──────────────────────────

    function test_FullLifecycle() public {
        uint8 hunger = 80;
        uint8 happiness = 50;
        uint8 energy = 50;
        uint8 age = 0;

        // Turn 1: Feed
        bytes memory output = _play(1, hunger, happiness, energy, age);
        hunger = uint8(output[0]);
        happiness = uint8(output[1]);
        energy = uint8(output[2]);
        age = uint8(output[3]);
        assertEq(hunger, 50);
        assertEq(happiness, 55);
        assertEq(energy, 50);
        assertEq(age, 1);

        // Turn 2: Play
        output = _play(2, hunger, happiness, energy, age);
        hunger = uint8(output[0]);
        happiness = uint8(output[1]);
        energy = uint8(output[2]);
        age = uint8(output[3]);
        assertEq(hunger, 60);
        assertEq(happiness, 75);
        assertEq(energy, 35);
        assertEq(age, 2);

        // Turn 3: Sleep
        output = _play(3, hunger, happiness, energy, age);
        hunger = uint8(output[0]);
        happiness = uint8(output[1]);
        energy = uint8(output[2]);
        age = uint8(output[3]);
        assertEq(hunger, 60);
        assertEq(happiness, 70);
        assertEq(energy, 65);
        assertEq(age, 3);

        assertEq(uint8(output[4]), 1);
    }

    // ─── Cartridge Registry Integration ──────────

    function test_TamagotchiRegisteredCorrectly() public view {
        (
            bytes memory program,
            string memory name,
            address creator,
            uint256 playCount
        ) = registry.getCartridge(tamagotchiId);

        assertEq(name, "Tamagotchi");
        assertEq(creator, address(this));
        assertGt(program.length, 0);
        assertEq(playCount, 0);
    }

    function test_PlayCountIncrements() public {
        _play(4, 50, 80, 60, 10);
        _play(1, 50, 80, 60, 10);
        _play(2, 50, 80, 60, 10);

        (, , , uint256 playCount) = registry.getCartridge(tamagotchiId);
        assertEq(playCount, 3);
    }
}
