version: '3.8'

services:
  brainfuck-vm:
    build: .
    ports:
      - "5173:5173" # Frontend
      - "8545:8545" # Anvil
    volumes:
      - .:/app
      - /app/frontend/node_modules
    environment:
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    stdin_open: true
    tty: true
    restart: unless-stopped
